name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
      name:default:
        description: 'Denis Muriuki'
        required: true
        default: 'World'
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  repository_dispatch:
    types: [run-action]
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types: [completed]
  push:
    branches: [main]

  push_request:
    branches: [main]
    